version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - supernetwork
    env_file:
      - .env
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - supernetwork
    env_file:
      - .env


networks:
  supernetwork:
    driver: bridge